### PR TITLE
Fix/labels

### LINKED ISSUE #38: Fix labelling
The `preprocessor` wrongfully understands a labels address' as its number of line pointing to instead of the actual byte.

### PR DESCRIPTION
**Pull request by felixhir**
Closes #38 

I feel like you could improve the code for `get_byte_amount_of_line` but I am not sure how.

### CODE REVIEW

File: emulator/src/kreator/preprocessor.rs [hunk 1]
```diff
@@ -344,21 +344,22 @@ fn generate_label_name(taken_names: &Vec<String>, generated_label_count: &mut u3
...
+        "ORG", "EQU", "SET", "END", "IF", "ENDIF", "MACRO", "ENDM", "B", "C", "D", "H", "L", "A", "SP", "PSW"
     ];
+    reserved_names.extend(&one_byte_labels);
+    reserved_names.extend(&two_byte_labels);
+    reserved_names.extend(&three_byte_labels);
+
     let mut temp_labels = Vec::new();
     let mut labels = HashMap::new();
-    let mut mem_address = 0;
+    let mut mem_address: i32 = 0;
```
Comment (moorts) [inline emulator/src/kreator/preprocessor.rs:357]: Make this u16 so you don't have to cast further down

File: emulator/src/kreator/preprocessor.rs [hunk 2]
```diff
@@ -393,6 +395,42 @@ fn get_labels(code: &Vec<String>) -> Result<HashMap<String, u16>, &'static str>
...
+    vec![
+        "MVI", "ADI", "ACI", "OUT", "SUI", "IN", "SBI", "ANI", "XRI", "ORI", "CPI"
+    ],
+    vec![
+        "LXI", "SHLD", "LHLD", "STA", "LDA", "JNZ", "JMP", "CNZ", "JZ", "CZ", "CALL", "JNC",
+        "CNC", "JC", "CC", "JPO", "CPO", "JPE", "CPE", "JP", "CP", "JM", "CM"
+    ])
+}
+
+fn get_byte_amount_of_line(line: &String) -> i32 {
```
Comment (moorts) [inline emulator/src/kreator/preprocessor.rs:414]: Return type therefore also should be u16

File: emulator/src/kreator/preprocessor.rs [hunk 3]
```diff
@@ -393,6 +395,42 @@ fn get_labels(code: &Vec<String>) -> Result<HashMap<String, u16>, &'static str>
...
+        if line.starts_with(opc) {
+            return 2;
+        }
+    }
+    for opc in &three_byte_labels {
+        if line.starts_with(opc) {
+            return 3;
+        }
+    }
+    0
```
Comment (moorts) [inline emulator/src/kreator/preprocessor.rs:431]: If this can't happen, maybe panic! or unreachable! it

**Review by moorts — CHANGES_REQUESTED** [review]

File: emulator/src/kreator/preprocessor.rs [hunk 4]
```diff
@@ -393,6 +395,42 @@ fn get_labels(code: &Vec<String>) -> Result<HashMap<String, u16>, &'static str>
...
+    ],
+    vec![
+        "LXI", "SHLD", "LHLD", "STA", "LDA", "JNZ", "JMP", "CNZ", "JZ", "CZ", "CALL", "JNC",
+        "CNC", "JC", "CC", "JPO", "CPO", "JPE", "CPE", "JP", "CP", "JM", "CM"
+    ])
+}
+
+fn get_byte_amount_of_line(line: &String) -> i32 {
+    let (one_byte_labels, two_byte_labels, three_byte_labels) = get_opc_by_byte_size();
+    for opc in &one_byte_labels {
```
Comment (moorts) [inline emulator/src/kreator/preprocessor.rs:416]: Possibly you could first get the first wird of the line (the opcode) and then just call x_byte_labels.contains(opcode) or something.

File: emulator/src/kreator/preprocessor.rs (hunk 3 above)
Comment (felixhir) [reply emulator/src/kreator/preprocessor.rs:431]: This can happen (and will happen) quite often. Because the labels have to be determined before the actual preprocessing lines like `ORG 10` or `IF 0` will still be in the code but should not affect the memory adress if my understanding is correct. So every line that is _not_ an instruction translated to byte code should simply have the value `0`

**Review by moorts — APPROVED** [review]
